### ISSUE TITLE
Task 9(G): Configuración de sistemas para incluir datos iniciales.

### ISSUE THREAD

**Issue by alepervaz** [alepervaz/Acme-L3-D02#5]
La configuración del sistema deberá de incluir como información inicial una divisa por defecto (EUR) y un conjunto de divisas válidas (EUR, USD, GBD).

Se deberá de crear una entidad configuración que contendrá dos atributos.

Se ha decidido que los dos atributos serán cadenas, uno de ellos será la divisa por defecto y el otro los posibles valores válidos de la divisa.

**Comment by alesanfe** [comment]
Añadir también los datos a initial-data.
